import os
from dotenv import load_dotenv 

load_dotenv()

CONSUMER_KEY=os.getenv('CONSUMER_KEY')
CONSUMER_SECRET=os.getenv('CONSUMER_SECRET')
ACCESS_TOKEN=os.getenv('ACCESS_TOKEN')
ACCESS_TOKEN_SECRET=os.getenv('ACCESS_TOKEN_SECRET')

MOKUPRO_CONSUMER_KEY=os.getenv('MOKUPRO_CONSUMER_KEY')
MOKUPRO_CONSUMER_SECRET=os.getenv('MOKUPRO_CONSUMER_SECRET')
MOKUPRO_ACCESS_TOKEN=os.getenv('MOKUPRO_ACCESS_TOKEN')
MOKUPRO_ACCESS_TOKEN_SECRET=os.getenv('MOKUPRO_ACCESS_TOKEN_SECRET')
